ci: publish common gh outputs during release
tumaysem/python-semantic-release pull request #3
Opened 2023-03-09 18:58 UTC by haritowa

This PR introduce change which publishes gh outputs during release if `--github` option is provided:
- `current_version`
- `current_release_version`
- `new_version`
- `should_bump`

2023-03-09 21:25 UTC, tumaysem requested changes
This is already implemented for cli command "semantic-version github".  Please use  it if you wish to recieve information without publish. On the otherhand cli command "semantic-version publish --github" will output published version and flag.
Can you clarify your case ?

2023-03-09 22:57 UTC, haritowa commented
Hello. I don't want to receive information without publish. I need a way to get the most recent version(either published or current) after the publish.

The current implementation publish outputs only if there is a new published version. And the `action.yml` doesn't provide a way to call `github` command.

One of the solutions may be to run both commands during the action.yml [run](https://github.com/tumaysem/python-semantic-release/blob/master/action.sh#L48), but why not just using already existing variables and publish them during the `release` command?

Another solution is to create a separate action which will call the `github action, but this is repetitive, forces to support another action/repo and could lead to double action docker build time(not sure here).

My pr doesn't introduce anything new, it uses already defined variables and publish already defined outputs.

2023-03-13 17:28 UTC, tumaysem reviewed
I believe you have already talked with @aasseman to resolve this with another way and he explained me about your aim. Please see this [action](https://github.com/semiotic-ai/autoagora-agents/blob/cb7ada2e88f2c5f8eb217d18759bcc49d423d4bb/.github/workflows/gh-pages.yml) which is very similiar what you want to achieve (get version without publish).

2023-03-13 19:36 UTC, haritowa commented
Yeah we did. I'll close the PR then

2023-03-13 19:36 UTC, closed without merging